routes/web.php
        Route::get('cambiar-preguntas-hijas/{tipo}/{padre?}/{pregunta?}',[PreguntasController::class, 'ChangeSubPregunta'])->name('cambiar-preguntas-hijas');
        Route::post('modal-secciones',[PreguntasController::class, 'ModalSeccionPregunta'])->name('modal-secciones');

        Route::post('actuallizar-orden-de-pregunta',[PreguntasController::class, 'UpdateOrden'])->name('update-carga-pregunta');

        Route::get('ordenar/{palabra?}',[PreguntasController::class, 'OrdenarPreguntas'])->name('ordenar-preguntas');


    });


    Route::prefix('tecnicos')->group(function () {
        Route::post('modal-permisos',[tecnicoController::class, 'ModaPermiso'])->name('modal-permisos');
        Route::post('modal-permisos-denegar',[tecnicoController::class, 'ModaPermisoDenegar'])->name('modal-permisos-denegar');
        Route::post('guardarAsignacion',[tecnicoController::class, 'guardarAsignacion'])->name('guardarAsignacion');
        Route::post('denegarPermiso',[tecnicoController::class, 'denegarPermiso'])->name('denegarPermiso');
        Route::get('eliminarAsignacion/{idTecnico}/{idPermiso}/{estado}',[tecnicoController::class, 'eliminarAsignacion'])->name('eliminarAsignacion');
        Route::get('listado',[tecnicoController::class, 'index'])->name('permisos-tecnico.index');
        Route::post('modal-permisos-informe',[tecnicoController::class, 'ModaPermisoInforme'])->name('modal-permisos-informe');
        Route::post('/vista-formulario', [tecnicoController::class, 'FormPermiso'])->name('FormPermiso');
        Route::post('/guardar-estado-preguntas/{idForm?}', [tecnicoController::class, 'SavePreguntasInforme'])->name('informe-save-preguntas');
        Route::post('/guardar-permiso-informe', [tecnicoController::class, 'GuardarPermisoInforme'])->name('guardar-permiso-informe');
    });

    Route::prefix('permisos')->group(function () {

        Route::get('subida-de-permisos',[PermisoController::class, 'ViewLoadFile'])->name('vload-file');
        Route::get('listado',[PermisoController::class, 'index'])->name('permisos.index');
        Route::get('generar-acta/{id}/{tipo?}',[PermisoController::class, 'GenerarActa'])->name('permisos.acta');
        Route::get('guardar-solvencia/{id}/{estado}/{pregunta?}',[PermisoController::class, 'GuardarSolvencia'])->name('save-solvencia');

        Route::get('paginador-seguimiento',[PermisoController::class, 'PageSeguimiento'])->name('page-seguimiento');
        Route::post('subida-de-archivo',[PermisoController::class, 'LoadFiles'])->name('permisos.load-file');
        Route::get('buscar/{palabra?}',[PermisoController::class, 'Buscar'])->name('buscar-permisos');

        Route::get('ordenar/{palabra?}',[PermisoController::class, 'Ordenar'])->name('ordenar-permisos');


        Route::get('detalle/{id}/{idForm}',[PermisoController::class, 'detalle'])->name('permisos.detalle');
        Route::get('detalle/preguntas/{idForm}/{IdPermiso}/{perf_id}',[PermisoController::class, 'detallePreguntas'])->name('permisos.detalle_preguntas');
        Route::get('permisos/detalle-tab-documentos/{id}',[PermisoController::class, 'tabDocumentos'])->name('permisos.detalle-tab-documentos');
        Route::get('permisos/detalle-tab-formularios/{id}',[PermisoController::class, 'tabFormularios'])->name('permisos.detalle-tab-formularios');
        Route::post('detalle-tab-docs/modal',[PermisoController::class, 'ShowModalE'])->name('tabDocs-modalE');
        Route::post('cambio-estados', [PermisoController::class, 'EstadosSolicitud'])->name('EstadosSolicitud');
        Route::post('modal-estados',[PermisoController::class, 'ModalEstados'])->name('modal-estados');
        Route::post('modal-edit',[PermisoController::class, 'ModalEditar'])->name('modal-edit');

        Route::post('modal-formulario',[PreguntasController::class, 'GetPreguntasForm'])->name('modal-formulario');
        Route::post('modal-formulario-acta',[PreguntasController::class, 'SubForms'])->name('modal-formulario-acta');
        Route::post('guardar',[PermisoController::class, 'GuardarFormulario'])->name('form-save');

        Route::get('seccion-formulario/{id?}',[PermisoController::class, 'SeccionesFormulario'])->name('secciones-formulario');
        Route::get('preguntas-detralle/{id?}',[PermisoController::class, 'PreguntasDetalle'])->name('preguntas-detalle');

        Route::post('modal-solventes',[PermisoController::class, 'ModaPermisoSolventes'])->name('modal-solvencia');


    });



    Route::prefix('opciones')->group(function () {

        Route::get('cambiar-pregunta/{pregunta}/{opcion}/{padre}',[OpcionController::class, 'CambiarOpcion'])->name('change-pregunta-option');
        Route::get('opciones/{pregunta}',[OpcionController::class, 'GetOpciones'])->name('get-opciones');
        Route::post('guardar',[OpcionController::class, 'SaveOpcion'])->name('save-opcion');
        Route::get('formulario/{Info}/{pregunta}',[OpcionController::class, 'FormOpciones'])->name('form-opciones');
        Route::get('eliminar-opcion/{Info}/{pregunta}', [OpcionController::class, 'DeleteOpcion'])->name('eliminar-opcion');
    });

    Route::prefix('estados')->group(function () {

        Route::get('data',[EstadoController::class, 'index'])->name('estados');
        Route::post('modal',[EstadoController::class, 'showModal'])->name('estado.modal');
        Route::post('guardar',[EstadoController::class, 'guardar'])->name('estado.guardar');
        Route::post('form-subestado',[EstadoController::class, 'GetSubEstado'])->name('subestado.form');
        Route::get('buscar/{palabra?}/{vista?}',[EstadoController::class, 'Buscar'])->name('buscar-estado');
        Route::get('estados-formulario/{id?}',[EstadoController::class, 'EstadosForm'])->name('estados-form');
        Route::post('obtener-subestados',[EstadoController::class, 'SubEstados'])->name('get-subestados');
        Route::get('eliminar-subestado/{estado}/{form}/{padre}',[EstadoController::class, 'EliminarEstado'])->name('eliminar-subestado');
        Route::post('buscar-estados',[EstadoController::class, 'SEstadoAsign'])->name('buscar-estados-asign');
        Route::post('modal-asign-estados',[EstadoController::class, 'TableAdd'])->name('modal-asign');
        Route::post('nuevo-estado-de-proceso',[EstadoController::class, 'AsignStatus'])->name('form-asign-status');

    });

    Route::prefix('formularios')->group(function () {

        Route::get('ordenar/{palabra?}',[FormularioController::class, 'OrdenarFormularios'])->name('ordenar-formularios');


        Route::get('buscar-pregunta/{id}/{palabra?}',[FormularioController::class, 'BuscarPreguntaAdd'])->name('buscar-preg-form');
        Route::get('buscar/{palabra?}',[FormularioController::class, 'Buscar'])->name('buscar-formulario');

        Route::get('datos',[FormularioController::class, 'TableInfo'])->name('formulario-info-table');
        Route::get('cambiar-pregunta/{tipo}/{form?}/{seccion?}',[FormularioController::class, 'CambiarSeccion'])->name('cambiar-preg-formulario');

        Route::get('secciones/{Info}',[FormularioController::class, 'GetSectionsForm'])->name('formulario-secciones');
        Route::get('/',[FormularioController::class, 'index'])->name('sector');
        Route::put('sector/{id}',[FormularioController::class, 'actualizar'])->name('sector.actualizar');

        Route::post('editar',[FormularioController::class, 'ShowEditModal'])->name('form-editar');
        Route::post('guardar',[FormularioController::class, 'EditSector'])->name('form-save');

        Route::post('actuallizar-orden-de-seccion',[FormularioController::class, 'UpdateOrden'])->name('update-carga-secciones');

    });

    Route::get('informacion-general/',[SucursalController::class, 'index'])->name('info-general');
    Route::post('sucursal/actualizar-informacion',[SucursalController::class, 'SaveInfo'])->name('sucursal-save');


    Route::prefix('administracion')->name('admin.')->group(function(){

        /**
         *
         * Rutas CRUD Usuarios
         *
         */
        Route::get('usuarios', [UsuarioController::class, 'index'])->name('user.index');
        Route::get('usuarios/create', [UsuarioController::class, 'create'])->name('user.create');
        Route::post('usuarios/store', [UsuarioController::class, 'SaveUser'])->name('user.store');
        // Route::get('usuarios/destroy/{id}', [UsersController::class, 'destroy'])->name('user.destroy');


        Route::get('usuarios/show/{id}', [UsuarioController::class, 'show'])->name('user.show');
        Route::get('usuarios/edit/{id}', [UsuarioController::class, 'edit'])->name('user.edit');
        Route::put('usuarios/update/{id}', [UsuarioController::class, 'update'])->name('user.update');

        /**
         *
         * Rutas CRUD Roles
         *
         */

        Route::resource('roles', RoleController::class)
                ->names('role')
                ->parameters(['permisos'=>'role']);

        /**
         *
         * Rutas CRUD Roles
         *
         */

        Route::resource('permisos', PermissionController::class)
                ->names('permission')
                ->parameters(['permisos' => 'permissions' ])
                ->only(['index','show']);

        /*
            CRUD PARA PRIVILEGIOS
        */


        Route::post('modal-permission', [PermissionController::class, 'ShowModal'])->name('permission-modal');
        Route::post('save-info-permission', [PermissionController::class, 'SaveInfo'])->name('save-permission');
        Route::get('delete-permission/{id}', [PermissionController::class, 'DeleteInfo'])->name('delete-permission');

    });


    Route::get('buscar-pregunta-de-la-seccion/{id}/{palabra?}',[seccionFormularioCont::class, 'BuscarPreguntaAdd'])->name('buscar-preg-seccion');
    Route::post('guardar',[seccionFormularioCont::class, 'guardar'])->name('seccion_formulario.guardar');
    // Route::get('buscar/{palabra?}',[seccionFormularioCont::class, 'Buscar'])->name('buscar-secciones');

});


// Routes for email

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasFactory, Notifiable;
    //use HasRoles;

    protected $table = "users";

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

resources/views/main/user/create.blade.php
@extends('layouts.template')
@section('pretittle', 'Vista general')
@section('tittle', 'Usuarios')
@section("scripts")

@endsection

@section('content')
@if ($errors->any())
<div class="alert alert-danger">
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif
@if (session()->has('flash'))
<div class="alert alert-info">{{ session('flash')}}</div>
@endif
{{-- <div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Register') }}</div>

<div class="card-body"> --}}

    <form method="POST" action="{{ route('admin.user.store') }}">
        @csrf

        <div class="form-group row">
            <label for="firstname" class="col-md-4 col-form-label text-md-right">Nombres</label>

            <div class="col-md-6">
                <input id="firstname" type="text" class="form-control @error('firstname') is-invalid @enderror" name="nombre" value="{{ old('firstname') }}" required autocomplete="firstname" autofocus>

                @error('firstname')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
        </div>
        <div class="form-group row">
            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail') }}</label>

            <div class="col-md-6">
                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="correo" value="{{ old('email') }}" required autocomplete="email">

                @error('email')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
        </div>

        <div class="form-group row">
            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

            <div class="col-md-6">
                <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="pass" required autocomplete="new-password">

                @error('password')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
        </div>

        <div class="form-group row">
            <label for="roles" class="col-md-4 col-form-label text-md-right">Asigne Roles al Usuario</label>
            <div class="col-md-6" style="margin-left: 15px;">
                @foreach ($roles as $role)
                <div>
                    <label class="form-check-label">
                        <input class="form-check-input" type="checkbox" name="roles[]" value="{{$role->id}}" {{-- @if($row->hasroleTo($role->id))
                                                checked
                                            @endif --}}>{{ $role->name }}
                        <em>({{ $role->description ?: 'Sin Descripcion' }})</em>
                    </label>
                </div>
                @endforeach
                <div class="col-md-6">
                </div>
                <div class="form-group row mb-0">
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                            {{ __('Register') }}
                        </button>
                    </div>
                </div>
    </form>
    {{-- </div>
            </div>
        </div>
    </div>
</div> --}}
@endsection

resources/views/main/user/edit.blade.php
@extends('layouts.template')
@section('pretittle', 'Vista general')
@section('tittle', 'Usuarios')
@section("scripts")

@endsection

@section('content')
@if ($errors->any())
<div class="alert alert-danger">
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif
@if (session()->has('flash'))
<div class="alert alert-info">{{ session('flash')}}</div>
@endif
{{-- <div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Register') }}</div>

<div class="card-body"> --}}

    <form method="post" action="{{ route('admin.user.update' , $row->usua_id) }}">
        {{ csrf_field() }}
        {{ method_field('PUT') }}

        <div class="form-group row">
            <label for="firstname" class="col-md-4 col-form-label text-md-right">{{ __('Nombres') }}</label>

            <div class="col-md-6">
                <input id="firstname" type="text" class="form-control @error('name') is-invalid @enderror" name="nombre" value="{{ $row->usua_nombre }}" required autocomplete="firstname" autofocus>

                @error('name')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
        </div>

        <div class="form-group row">
            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

            <div class="col-md-6">
                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="correo" value="{{ $row->usua_mail }}" required autocomplete="email">

                @error('email')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
        </div>


        <div class="form-group row">
            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

            <div class="col-md-6">
                <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="pass" autocomplete="new-password">
                @error('password')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
        </div>


<div class="form-group row">
    <label for="roles" class="col-md-4 col-form-label text-md-right">Asigne Roles al Usuario</label>
    <div class="col-md-6" style="margin-left: 15px;">
        @foreach ($roles as $role)
        <div>
            <label class="form-check-label">
                <input class="form-check-input" type="checkbox" name="roles[]" value="{{$role->id}}" @if($row->hasRole($role->id))
                checked
                @endif
                >{{ $role->name }}
                <em>({{ $role->description ?: 'Sin Descripcion' }})</em>
            </label>
        </div>
        @endforeach
        <div class="col-md-6">
        </div>
        <div class="form-group row mb-0">
            <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">Actualizar </button>
            </div>
        </div>
        </form>
        {{-- </div>
            </div>
        </div>
    </div>
</div> --}}
@endsection

resources/views/main/user/index.blade.php
@extends('layouts.template')
@section('pretittle', 'Vista general')
@section('tittle', 'USUARIOS')
@section("scripts")

@endsection

@section('content')


<x-table>
    @slot('idTabla')
    tablePermisos
    @endslot

    @slot('titulo')
    Listado de permisos
    @endslot


    @slot('accionBuscar')
        onkeyup="if(event.keyCode == 13) MakeRequestData('{{route('buscar-preguntas')}}' + '/' + $(this).val() , '#tablePermisos', true)"
    @endslot

    @slot('btnAdicionales')

        <a href="{{ route('admin.user.create') }}" title="Crear Usuario" style="padding-bottom:10px!important;"
        class="btn btn-success">
            <i class="fa fa-plus"></i> &nbsp; Agregar
        </a>
    @endslot


    @slot('header')
        <th>Nombre</th>
        <th>Email</th>
        <th>Roles</th>
        <th>Acciones</th>
    @endslot

    @slot('body')
        @foreach($rows as $row)
            <tr>
                <td>{{ $row->usua_nombre }}</td>
                <td>{{ $row->usua_mail }}</td>
                <td>
                    @if($row->roles->isNotEmpty())
                    @foreach($row->roles as $role)
                    {{$role->name}}
                    @endforeach
                    @endif
                </td>
                <td>

                    <a href="{{ route('admin.user.show', $row->usua_id) }}" class="btn btn-primary">Mostrar</a>
                    <a href="{{ route('admin.user.edit', $row->usua_id) }}" class="btn btn-secondary">Editar</a>

                </td>
            </tr>
        @endforeach
    @endslot

</x-table>

@endsection

resources/views/main/user/show.blade.php
@extends('layouts.template')
@section('pretittle', 'Vista general')
@section('tittle', 'Usuarios')
@section("scripts")

@endsection

@section('content')
<div class="row">
        <div class="col-12 col-md-4">
            <p><b>Nombre</b> : <br>{{ $row->usua_nombre }}</p>
        </div>
        <div class="col-12 col-md-8">
            <p><b>Email</b> : <br>{{ $row->usua_mail }}</p>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <h4>Roles Asignados</h4>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Descripción</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($row->roles as $role)
                        @if($row->hasRole($role->id))
                            <tr>
                                <td>{{ $role->name }}</td>
                                <td>{{ $role->description }}</td>
                            </tr>
                        @endif
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection